FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git && \
    git clone https://github.com/laramies/theHarvester.git /app && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install flask

COPY harvester/theHarvesterApi.py /app/theHarvesterApi.py

EXPOSE 5000

CMD ["python", "theHarvesterApi.py"]